services:
  tegola_server:
    build:
      context: ./tegola_server
      dockerfile: Dockerfile
    container_name: tegola_server
    ports:
      - "8080:8080"
    volumes:
      - ./tegola_server/config.toml:/tegola/config.toml
    networks:
      - navigation-network

  valhalla_server:
    build:
      context: ./valhalla_server
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: valhalla_server
    volumes:
      - ./valhalla_server/valhalla.json:/data/valhalla/valhalla.json
    ports:
      - "8002:8002"

  rust_server:
    build:
      context: ./rust_server
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/osm
    container_name: rust_server
    environment:
      DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/osm
    ports:
      - "8000:8000"
    depends_on:
      - tegola_server
      - valhalla_server
    networks:
      - navigation-network
    volumes:
      - ./rust_server/src:/app/src

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8081:8081" # NGINX가 외부에 노출될 포트
    depends_on:
      - tegola_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # NGINX 설정 파일
    networks:
      - navigation-network

networks:
  navigation-network:
    external: true

